"""Remote data asset registry (auto-generated by data_registry.py).

Do not edit manually.  Re-run ``scripts/data_registry.py generate``
to update after uploading new data.

After publishing to **production** Zenodo, replace sandbox URLs with
production URLs and update the record ID.
"""

DATA_DIR_NAME = "complexheatmap_data"
CACHE_DIR_NAME = "complexheatmap_py"

REGISTRY: dict[str, dict[str, str]] = {
    "upset_peak_m.csv": {
        "url": "https://sandbox.zenodo.org/records/487400/files/upset_peak_m.csv?download=1",
        "sha256": "c8774ef9e6208cf34c652ec44b18bc1923b303640e3aee59a00b448271052b4f",
    },
}
